In [24]:
import numpy as np
import pandas as pd
from pycaret.classification import *

In [25]:
np.random.seed(42)
rows = 50

# Create sample data with 10 columns.
data = {
    "num1": np.random.randint(0, 100, size=rows),
    "num2": np.random.randn(rows) * 10,
    "cat1": np.random.choice(["apple", "banana", "cherry"], size=rows),
    "cat2": np.random.choice(["red", "green", "blue"], size=rows),
    "num3": np.random.uniform(0, 50, size=rows),
    "num4": np.random.randint(0, 200, size=rows),
    "text": [f"Sample {i}" for i in range(rows)],
    "bool": np.random.choice([True, False], size=rows),
    "num5": np.random.randn(rows) * 5,
    "cat3": np.random.choice(["X", "Y", "Z"], size=rows)
}
df = pd.DataFrame(data)

for col in ["num2", "num3", "text"]:
    missing_indices = np.random.choice(df.index, size=5, replace=False)
    df.loc[missing_indices, col] = np.nan

df.loc[10] = df.loc[0]
df.loc[20] = df.loc[0]

data = df.copy()
data

,num1,num2,cat1,cat2,num3,num4,text,bool,num5,cat3
0,51,-20.267196,cherry,red,33.606777,98,Sample 0,True,0.291044,Y
1,92,11.194236,banana,red,NaN,152,Sample 1,False,-5.714851,Y
2,14,7.791926,cherry,red,11.881877,92,Sample 2,True,1.788937,X
3,71,-11.010978,apple,blue,36.410817,145,Sample 3,False,2.803923,X
4,60,11.302282,apple,green,18.389157,127,Sample 4,True,5.415256,X
5,20,NaN,banana,red,NaN,109,Sample 5,False,5.269010,X
6,82,-3.864730,cherry,red,31.676486,81,Sample 6,False,-6.888347,X
7,86,-11.587702,cherry,red,26.788734,193,Sample 7,False,-4.689125,Z
8,74,5.661128,banana,blue,4.514489,53,Sample 8,True,2.575176,Z
9,74,-7.044535,cherry,blue,41.765125,162,Sample 9,False,2.568930,X
10,51,-20.267196,cherry,red,33.606777,98,Sample 0,True,0.291044,Y
11,99,-3.531167,apple,blue,9.325926,168,Sample 11,False,19.263657,X
12,23,-4.614657,cherry,red,2.038757,160,Sample 12,True,2.854453,Z
13,2,0.666573,cherry,green,29.544647,67,Sample 13,False,5.677828,Z
14,21,-1.762857,banana,red,33.878218,32,Sample 14,True,4.770009,Y
15,52,12.008928,banana,red,0.829391,141,Sample 15,True,3.256956,Z
16,1,6.983989,apple,blue,25.604653,20,Sample 16,False,-1.576346,X
17,87,-1.716288,cherry,green,11.324789,47,Sample 17,True,3.794846,Y
18,29,-9.071866,cherry,blue,32.258640,147,Sample 18,True,-3.864126,X
19,37,11.886257,cherry,blue,8.718321,127,NaN,False,-1.184093,X
20,51,-20.267196,cherry,red,33.606777,98,Sample 0,True,0.291044,Y
21,63,NaN,apple,red,19.336767,134,Sample 21,True,0.409371,X
22,59,2.634860,banana,red,46.836499,194,Sample 22,True,11.573293,Z
23,20,16.417711,apple,green,6.876047,144,Sample 23,False,-9.336326,X
24,32,4.608163,cherry,red,17.053318,127,NaN,True,3.431301,Y
25,75,NaN,cherry,green,5.673676,32,Sample 25,False,-8.063579,Y
26,57,-15.099573,apple,green,46.234681,175,Sample 26,True,-2.359659,Y
27,21,7.215025,cherry,blue,43.866968,186,Sample 27,True,5.444753,X
28,88,-8.434199,cherry,green,NaN,114,Sample 28,True,0.321400,Y
29,48,-5.133254,apple,blue,32.999202,118,Sample 29,False,-5.388724,Y
30,90,-0.435368,apple,red,40.861110,21,Sample 30,True,-3.576519,X
31,58,-2.753009,cherry,red,27.760041,157,NaN,True,3.397989,Z
32,41,-15.630668,cherry,red,26.482529,37,Sample 32,False,-3.651833,X
33,91,-7.956310,cherry,red,12.092615,108,Sample 33,True,1.082293,Y
34,59,9.305844,banana,blue,4.655138,50,Sample 34,False,0.227859,Y
35,79,6.777674,banana,red,44.860788,181,Sample 35,False,-3.258002,X
36,14,6.984403,banana,green,45.020903,7,NaN,True,10.719720,Z
37,61,1.736021,apple,green,31.655073,26,Sample 37,False,3.169595,Y
38,61,6.622845,banana,green,16.951490,26,Sample 38,True,-10.125713,Y
39,46,2.411222,apple,blue,17.460479,20,Sample 39,False,0.932272,Y
40,61,-1.682051,apple,red,36.297784,29,NaN,False,-3.308932,X
41,50,11.647686,banana,red,NaN,96,Sample 41,True,4.262167,Y
42,54,NaN,banana,red,44.354321,27,Sample 42,False,-3.962604,Z
43,63,-7.696678,banana,blue,38.993777,110,Sample 43,False,-0.573682,Y
44,2,12.121723,cherry,green,NaN,191,Sample 44,False,2.524936,Y
45,50,12.334968,banana,green,4.206998,196,Sample 45,False,4.328776,Z
46,6,-15.741553,cherry,red,8.081436,60,Sample 46,False,-6.001482,Y
47,20,6.379529,apple,green,44.927709,47,Sample 47,True,-1.672506,X
48,72,-20.444230,cherry,green,30.321453,146,Sample 48,False,-2.374727,X
49,38,10.694809,banana,blue,0.459853,3,Sample 49,True,-3.266646,X

In [26]:
exp = setup(
    data=data, 
    target='cat3', 
    session_id=42, 
    verbose=False,
    imputation_type='simple',      # 使用简单的缺失值填充方式
    numeric_imputation='mean',       # 数值型数据用均值填充
    categorical_imputation='mode'    # 类别型数据用众数填充
)
    
# 获取预处理后的训练数据
X = get_config('X_train')
y = get_config('y_train')
    
# 合并特征和目标列，形成预处理后的完整数据集
processed_data = X.copy()
processed_data['cat3'] = y
processed_data

,num1,num2,cat1,cat2,num3,num4,text,bool,num5,cat3
18,29,-9.071866,cherry,blue,32.258640,147,Sample 18,True,-3.864126,X
24,32,4.608163,cherry,red,17.053318,127,NaN,True,3.431301,Y
17,87,-1.716288,cherry,green,11.324789,47,Sample 17,True,3.794846,Y
2,14,7.791926,cherry,red,11.881877,92,Sample 2,True,1.788937,X
22,59,2.634861,banana,red,46.836498,194,Sample 22,True,11.573293,Z
37,61,1.736021,apple,green,31.655073,26,Sample 37,False,3.169595,Y
30,90,-0.435368,apple,red,40.861111,21,Sample 30,True,-3.576519,X
13,2,0.666573,cherry,green,29.544647,67,Sample 13,False,5.677828,Z
19,37,11.886257,cherry,blue,8.718322,127,NaN,False,-1.184093,X
25,75,NaN,cherry,green,5.673676,32,Sample 25,False,-8.063580,Y
41,50,11.647686,banana,red,NaN,96,Sample 41,True,4.262167,Y
36,14,6.984403,banana,green,45.020905,7,NaN,True,10.719721,Z
40,61,-1.682051,apple,red,36.297783,29,NaN,False,-3.308932,X
10,51,-20.267197,cherry,red,33.606777,98,Sample 0,True,0.291044,Y
9,74,-7.044535,cherry,blue,41.765125,162,Sample 9,False,2.568930,X
14,21,-1.762857,banana,red,33.878220,32,Sample 14,True,4.770009,Y
45,50,12.334968,banana,green,4.206998,196,Sample 45,False,4.328776,Z
38,61,6.622845,banana,green,16.951490,26,Sample 38,True,-10.125713,Y
7,86,-11.587703,cherry,red,26.788734,193,Sample 7,False,-4.689125,Z
20,51,-20.267197,cherry,red,33.606777,98,Sample 0,True,0.291044,Y
3,71,-11.010978,apple,blue,36.410816,145,Sample 3,False,2.803923,X
39,46,2.411222,apple,blue,17.460478,20,Sample 39,False,0.932272,Y
49,38,10.694809,banana,blue,0.459853,3,Sample 49,True,-3.266646,X
35,79,6.777674,banana,red,44.860786,181,Sample 35,False,-3.258002,X
12,23,-4.614657,cherry,red,2.038757,160,Sample 12,True,2.854453,Z
5,20,NaN,banana,red,NaN,109,Sample 5,False,5.269010,X
4,60,11.302282,apple,green,18.389156,127,Sample 4,True,5.415256,X
23,20,16.417711,apple,green,6.876047,144,Sample 23,False,-9.336326,X
15,52,12.008927,banana,red,0.829391,141,Sample 15,True,3.256956,Z
46,6,-15.741553,cherry,red,8.081436,60,Sample 46,False,-6.001482,Y
29,48,-5.133254,apple,blue,32.999203,118,Sample 29,False,-5.388724,Y
34,59,9.305844,banana,blue,4.655138,50,Sample 34,False,0.227859,Y
47,20,6.379529,apple,green,44.927708,47,Sample 47,True,-1.672506,X
28,88,-8.434199,cherry,green,NaN,114,Sample 28,True,0.321400,Y
48,72,-20.444231,cherry,green,30.321453,146,Sample 48,False,-2.374727,X

In [27]:
# Remove duplicate rows
data = data.drop_duplicates()
# Remove Leading/Trailing Spaces
data.columns = data.columns.str.strip()

In [28]:
# Define maximum allowed categories (less than 1% of rows)
max_categories_threshold = int(len(data) * 0.01)

# Identify categorical columns (object or category dtypes) that meet the threshold
eligible_cat_features = [
    col for col in data.select_dtypes(include=['object', 'category', 'bool']).columns
    if data[col].nunique() <= max_categories_threshold]

print("Eligible categorical features for encoding:", eligible_cat_features)

# Encode each eligible categorical column using pd.factorize
for col in eligible_cat_features:
    data[col], _ = pd.factorize(data[col])

Eligible categorical features for encoding: []

In [29]:
target = 'null'
# Transit target from front end

# Detect target column if not provided
if target == 'null' or target not in data.columns:
    def detect_target_column(df):
        possible_target = None
        for col in df.columns:
            unique_values = df[col].nunique()
            # Check if the column has no missing values and is suitable for classification
            if unique_values == 2 and df[col].isnull().sum() == 0:  # Binary classification without missing values
                possible_target = col
            elif 2 < unique_values < len(data) * 0.01 and df[col].isnull().sum() == 0:  # Multi-class classification without missing values
                possible_target = col
        return possible_target # Target column is more possible on the right side
    
    target = detect_target_column(data)

# find if target is found
if target:
    print(f"Detected target column: {target}")
else:
    print("No suitable target column detected. Please specify it manually.")

if target in eligible_cat_features:
    eligible_cat_features.remove(target)

Detected target column: bool

In [30]:
import re

def detect_ignore_features(df, keywords=None):
    if keywords is None:
        # Only ignore columns that are very likely identifiers or irrelevant
        keywords = ['row', 'id', 'name']
        
    ignore_features = []
    
    for col in df.columns:
        # Check if column name contains any of the keywords
        if any(re.search(keyword, col, flags=re.IGNORECASE) for keyword in keywords):
            ignore_features.append(col)
    
    return ignore_features

# Usage with your DataFrame
ignore_features = detect_ignore_features(data)
print("Automatically detected ignore features:", ignore_features)

Automatically detected ignore features: []

In [31]:
clf = setup(
    data=data,
    target=target,
    
    # Data cleaning configuration
    numeric_imputation="median",  # Fill missing numerical values with the median
    categorical_imputation='mode',  # Fill missing categorical values with the mode
    remove_multicollinearity=True,  # Remove multicollinearity features
    multicollinearity_threshold=1.0, 
    remove_outliers=True,  # Automatically handle outliers using the IQR method
    outliers_threshold=0.05,  # Outlier detection threshold
    fold_strategy='stratifiedkfold',  # Use stratified K-fold cross-validation
    categorical_features=eligible_cat_features,
    normalize=True,

    # Categorical feature handling
    ignore_features=ignore_features,  # Ignore irrelevant features
    
    # Other automation settings
    fix_imbalance=True,  # Automatically handle class imbalance
    session_id=42  # Random seed
)

In [32]:
# Get the cleaned data
cleaned_data = get_config('X_train')  # Retrieve the cleaned data (excluding the target column)
cleaned_data[target] = get_config('y_train')  # Re-add the target column

cleaned_data

,num1,num2,cat1,cat2,num3,num4,text,num5,cat3,bool
41,50,11.647686,banana,red,NaN,96,Sample 41,4.262167,Y,True
17,87,-1.716288,cherry,green,11.324789,47,Sample 17,3.794846,Y,True
33,91,-7.956310,cherry,red,12.092614,108,Sample 33,1.082293,Y,True
39,46,2.411222,apple,blue,17.460478,20,Sample 39,0.932272,Y,False
25,75,NaN,cherry,green,5.673676,32,Sample 25,-8.063580,Y,False
5,20,NaN,banana,red,NaN,109,Sample 5,5.269010,X,False
9,74,-7.044535,cherry,blue,41.765125,162,Sample 9,2.568930,X,False
8,74,5.661128,banana,blue,4.514489,53,Sample 8,2.575176,Z,True
19,37,11.886257,cherry,blue,8.718322,127,NaN,-1.184093,X,False
35,79,6.777674,banana,red,44.860786,181,Sample 35,-3.258002,X,False
43,63,-7.696678,banana,blue,38.993778,110,Sample 43,-0.573682,Y,False
2,14,7.791926,cherry,red,11.881877,92,Sample 2,1.788937,X,True
12,23,-4.614657,cherry,red,2.038757,160,Sample 12,2.854453,Z,True
27,21,7.215024,cherry,blue,43.866966,186,Sample 27,5.444753,X,True
16,1,6.983989,apple,blue,25.604652,20,Sample 16,-1.576346,X,False
4,60,11.302282,apple,green,18.389156,127,Sample 4,5.415256,X,True
1,92,11.194236,banana,red,NaN,152,Sample 1,-5.714851,Y,False
22,59,2.634861,banana,red,46.836498,194,Sample 22,11.573293,Z,True
3,71,-11.010978,apple,blue,36.410816,145,Sample 3,2.803923,X,False
29,48,-5.133254,apple,blue,32.999203,118,Sample 29,-5.388724,Y,False
32,41,-15.630668,cherry,red,26.482529,37,Sample 32,-3.651833,X,False
7,86,-11.587703,cherry,red,26.788734,193,Sample 7,-4.689125,Z,False
14,21,-1.762857,banana,red,33.878220,32,Sample 14,4.770009,Y,True
37,61,1.736021,apple,green,31.655073,26,Sample 37,3.169595,Y,False
0,51,-20.267197,cherry,red,33.606777,98,Sample 0,0.291044,Y,True
38,61,6.622845,banana,green,16.951490,26,Sample 38,-10.125713,Y,True
45,50,12.334968,banana,green,4.206998,196,Sample 45,4.328776,Z,False
18,29,-9.071866,cherry,blue,32.258640,147,Sample 18,-3.864126,X,True
36,14,6.984403,banana,green,45.020905,7,NaN,10.719721,Z,True
6,82,-3.864729,cherry,red,31.676485,81,Sample 6,-6.888347,X,False
15,52,12.008927,banana,red,0.829391,141,Sample 15,3.256956,Z,True
26,57,-15.099573,apple,green,46.234680,175,Sample 26,-2.359659,Y,True
46,6,-15.741553,cherry,red,8.081436,60,Sample 46,-6.001482,Y,False

In [33]:
# # Retrieve and compare all models
# compare_models(sort='AUC')

# # Get the comparison results
# model_comparison = pull()
# print(model_comparison)