In [ ]:
import pandas as pd
import numpy as np
from ScanResult import *
from data_scan import *
from apply_scan_results import *

In [14]:
np.random.seed(42)
rows = 50

# Create sample data with 10 columns.
data = {
    "num1": np.random.randint(0, 100, size=rows),
    "num2": np.random.randn(rows) * 10,
    "cat1": np.random.choice(["apple", "banana", "cherry"], size=rows),
    "cat2": np.random.choice(["red", "green", "blue"], size=rows),
    "num3": np.random.uniform(0, 50, size=rows),
    "num4": np.random.randint(0, 200, size=rows),
    "text": [f"Sample {i}" for i in range(rows)],
    "bool": np.random.choice([True, False], size=rows),
    "num5": np.random.randn(rows) * 5,
    "cat3": np.random.choice(["X", "Y", "Z"], size=rows)
}
df = pd.DataFrame(data)

for col in ["num2", "num3", "text"]:
    missing_indices = np.random.choice(df.index, size=5, replace=False)
    df.loc[missing_indices, col] = np.nan

df.loc[10] = df.loc[0]
df.loc[20] = df.loc[0]

df1 = df.copy()
df2 = df.copy()
df

,num1,num2,cat1,cat2,num3,num4,text,bool,num5,cat3
0,51,-20.267196,cherry,red,33.606777,98,Sample 0,True,0.291044,Y
1,92,11.194236,banana,red,NaN,152,Sample 1,False,-5.714851,Y
2,14,7.791926,cherry,red,11.881877,92,Sample 2,True,1.788937,X
3,71,-11.010978,apple,blue,36.410817,145,Sample 3,False,2.803923,X
4,60,11.302282,apple,green,18.389157,127,Sample 4,True,5.415256,X
5,20,NaN,banana,red,NaN,109,Sample 5,False,5.269010,X
6,82,-3.864730,cherry,red,31.676486,81,Sample 6,False,-6.888347,X
7,86,-11.587702,cherry,red,26.788734,193,Sample 7,False,-4.689125,Z
8,74,5.661128,banana,blue,4.514489,53,Sample 8,True,2.575176,Z
9,74,-7.044535,cherry,blue,41.765125,162,Sample 9,False,2.568930,X
10,51,-20.267196,cherry,red,33.606777,98,Sample 0,True,0.291044,Y
11,99,-3.531167,apple,blue,9.325926,168,Sample 11,False,19.263657,X
12,23,-4.614657,cherry,red,2.038757,160,Sample 12,True,2.854453,Z
13,2,0.666573,cherry,green,29.544647,67,Sample 13,False,5.677828,Z
14,21,-1.762857,banana,red,33.878218,32,Sample 14,True,4.770009,Y
15,52,12.008928,banana,red,0.829391,141,Sample 15,True,3.256956,Z
16,1,6.983989,apple,blue,25.604653,20,Sample 16,False,-1.576346,X
17,87,-1.716288,cherry,green,11.324789,47,Sample 17,True,3.794846,Y
18,29,-9.071866,cherry,blue,32.258640,147,Sample 18,True,-3.864126,X
19,37,11.886257,cherry,blue,8.718321,127,NaN,False,-1.184093,X
20,51,-20.267196,cherry,red,33.606777,98,Sample 0,True,0.291044,Y
21,63,NaN,apple,red,19.336767,134,Sample 21,True,0.409371,X
22,59,2.634860,banana,red,46.836499,194,Sample 22,True,11.573293,Z
23,20,16.417711,apple,green,6.876047,144,Sample 23,False,-9.336326,X
24,32,4.608163,cherry,red,17.053318,127,NaN,True,3.431301,Y
25,75,NaN,cherry,green,5.673676,32,Sample 25,False,-8.063579,Y
26,57,-15.099573,apple,green,46.234681,175,Sample 26,True,-2.359659,Y
27,21,7.215025,cherry,blue,43.866968,186,Sample 27,True,5.444753,X
28,88,-8.434199,cherry,green,NaN,114,Sample 28,True,0.321400,Y
29,48,-5.133254,apple,blue,32.999202,118,Sample 29,False,-5.388724,Y
30,90,-0.435368,apple,red,40.861110,21,Sample 30,True,-3.576519,X
31,58,-2.753009,cherry,red,27.760041,157,NaN,True,3.397989,Z
32,41,-15.630668,cherry,red,26.482529,37,Sample 32,False,-3.651833,X
33,91,-7.956310,cherry,red,12.092615,108,Sample 33,True,1.082293,Y
34,59,9.305844,banana,blue,4.655138,50,Sample 34,False,0.227859,Y
35,79,6.777674,banana,red,44.860788,181,Sample 35,False,-3.258002,X
36,14,6.984403,banana,green,45.020903,7,NaN,True,10.719720,Z
37,61,1.736021,apple,green,31.655073,26,Sample 37,False,3.169595,Y
38,61,6.622845,banana,green,16.951490,26,Sample 38,True,-10.125713,Y
39,46,2.411222,apple,blue,17.460479,20,Sample 39,False,0.932272,Y
40,61,-1.682051,apple,red,36.297784,29,NaN,False,-3.308932,X
41,50,11.647686,banana,red,NaN,96,Sample 41,True,4.262167,Y
42,54,NaN,banana,red,44.354321,27,Sample 42,False,-3.962604,Z
43,63,-7.696678,banana,blue,38.993777,110,Sample 43,False,-0.573682,Y
44,2,12.121723,cherry,green,NaN,191,Sample 44,False,2.524936,Y
45,50,12.334968,banana,green,4.206998,196,Sample 45,False,4.328776,Z
46,6,-15.741553,cherry,red,8.081436,60,Sample 46,False,-6.001482,Y
47,20,6.379529,apple,green,44.927709,47,Sample 47,True,-1.672506,X
48,72,-20.444230,cherry,green,30.321453,146,Sample 48,False,-2.374727,X
49,38,10.694809,banana,blue,0.459853,3,Sample 49,True,-3.266646,X

In [15]:
scan_results = []
scan_results.extend(scan_df_for_duplicates(df1))
scan_results.extend(scan_df_for_missing(df1))
scan_results.extend(scan_df_for_outliers(df1))
scan_results.extend(scan_df_for_categorical(df1))

scan_results.extend(scan_df_for_target(df1, target=51))

scan_results

[ScanResult(row=10, col=-1, message='Row 11 is duplicated', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Duplication Remover', description='Remove the duplicated rows', cleaner='remove', cleaner_id=0, activate=True, data=None), ScanResultAction(title='Duplication Remover', description='Keep the duplicated rows', cleaner='keep', cleaner_id=1, activate=True, data=None)]),
 ScanResult(row=20, col=-1, message='Row 21 is duplicated', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Duplication Remover', description='Remove the duplicated rows', cleaner='remove', cleaner_id=2, activate=True, data=None), ScanResultAction(title='Duplication Remover', description='Keep the duplicated rows', cleaner='keep', cleaner_id=3, activate=True, data=None)]),
 ScanResult(row=1, col=num3, message='Missing value in row 2, column 'num3'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Missing Value Filler', description='Fill with mean value', cleaner='mean', cleaner_id=0, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with median value', cleaner='median', cleaner_id=1, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with most frequent value', cleaner='mode', cleaner_id=2, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with previous value', cleaner='ffill', cleaner_id=3, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with next value', cleaner='bfill', cleaner_id=4, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Delete the row', cleaner='delete', cleaner_id=5, activate=True, data=None)]),
 ScanResult(row=5, col=num2, message='Missing value in row 6, column 'num2'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Missing Value Filler', description='Fill with mean value', cleaner='mean', cleaner_id=6, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with median value', cleaner='median', cleaner_id=7, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with most frequent value', cleaner='mode', cleaner_id=8, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with previous value', cleaner='ffill', cleaner_id=9, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with next value', cleaner='bfill', cleaner_id=10, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Delete the row', cleaner='delete', cleaner_id=11, activate=True, data=None)]),
 ScanResult(row=5, col=num3, message='Missing value in row 6, column 'num3'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Missing Value Filler', description='Fill with mean value', cleaner='mean', cleaner_id=12, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with median value', cleaner='median', cleaner_id=13, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with most frequent value', cleaner='mode', cleaner_id=14, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with previous value', cleaner='ffill', cleaner_id=15, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with next value', cleaner='bfill', cleaner_id=16, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Delete the row', cleaner='delete', cleaner_id=17, activate=True, data=None)]),
 ScanResult(row=19, col=text, message='Missing value in row 20, column 'text'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Missing Value Filler', description='Fill with most frequent value', cleaner='mode', cleaner_id=18, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with previous value', cleaner='ffill', cleaner_id=19, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with next value', cleaner='bfill', cleaner_id=20, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Delete the row', cleaner='delete', cleaner_id=21, activate=True, data=None)]),
 ScanResult(row=21, col=num2, message='Missing value in row 22, column 'num2'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Missing Value Filler', description='Fill with mean value', cleaner='mean', cleaner_id=22, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with median value', cleaner='median', cleaner_id=23, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with most frequent value', cleaner='mode', cleaner_id=24, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with previous value', cleaner='ffill', cleaner_id=25, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with next value', cleaner='bfill', cleaner_id=26, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Delete the row', cleaner='delete', cleaner_id=27, activate=True, data=None)]),
 ScanResult(row=24, col=text, message='Missing value in row 25, column 'text'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Missing Value Filler', description='Fill with most frequent value', cleaner='mode', cleaner_id=28, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with previous value', cleaner='ffill', cleaner_id=29, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with next value', cleaner='bfill', cleaner_id=30, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Delete the row', cleaner='delete', cleaner_id=31, activate=True, data=None)]),
 ScanResult(row=25, col=num2, message='Missing value in row 26, column 'num2'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Missing Value Filler', description='Fill with mean value', cleaner='mean', cleaner_id=32, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with median value', cleaner='median', cleaner_id=33, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with most frequent value', cleaner='mode', cleaner_id=34, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with previous value', cleaner='ffill', cleaner_id=35, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with next value', cleaner='bfill', cleaner_id=36, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Delete the row', cleaner='delete', cleaner_id=37, activate=True, data=None)]),
 ScanResult(row=28, col=num3, message='Missing value in row 29, column 'num3'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Missing Value Filler', description='Fill with mean value', cleaner='mean', cleaner_id=38, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with median value', cleaner='median', cleaner_id=39, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with most frequent value', cleaner='mode', cleaner_id=40, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with previous value', cleaner='ffill', cleaner_id=41, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with next value', cleaner='bfill', cleaner_id=42, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Delete the row', cleaner='delete', cleaner_id=43, activate=True, data=None)]),
 ScanResult(row=31, col=text, message='Missing value in row 32, column 'text'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Missing Value Filler', description='Fill with most frequent value', cleaner='mode', cleaner_id=44, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with previous value', cleaner='ffill', cleaner_id=45, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with next value', cleaner='bfill', cleaner_id=46, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Delete the row', cleaner='delete', cleaner_id=47, activate=True, data=None)]),
 ScanResult(row=36, col=text, message='Missing value in row 37, column 'text'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Missing Value Filler', description='Fill with most frequent value', cleaner='mode', cleaner_id=48, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with previous value', cleaner='ffill', cleaner_id=49, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with next value', cleaner='bfill', cleaner_id=50, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Delete the row', cleaner='delete', cleaner_id=51, activate=True, data=None)]),
 ScanResult(row=40, col=text, message='Missing value in row 41, column 'text'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Missing Value Filler', description='Fill with most frequent value', cleaner='mode', cleaner_id=52, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with previous value', cleaner='ffill', cleaner_id=53, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with next value', cleaner='bfill', cleaner_id=54, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Delete the row', cleaner='delete', cleaner_id=55, activate=True, data=None)]),
 ScanResult(row=41, col=num3, message='Missing value in row 42, column 'num3'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Missing Value Filler', description='Fill with mean value', cleaner='mean', cleaner_id=56, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with median value', cleaner='median', cleaner_id=57, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with most frequent value', cleaner='mode', cleaner_id=58, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with previous value', cleaner='ffill', cleaner_id=59, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with next value', cleaner='bfill', cleaner_id=60, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Delete the row', cleaner='delete', cleaner_id=61, activate=True, data=None)]),
 ScanResult(row=42, col=num2, message='Missing value in row 43, column 'num2'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Missing Value Filler', description='Fill with mean value', cleaner='mean', cleaner_id=62, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with median value', cleaner='median', cleaner_id=63, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with most frequent value', cleaner='mode', cleaner_id=64, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with previous value', cleaner='ffill', cleaner_id=65, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with next value', cleaner='bfill', cleaner_id=66, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Delete the row', cleaner='delete', cleaner_id=67, activate=True, data=None)]),
 ScanResult(row=44, col=num3, message='Missing value in row 45, column 'num3'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Missing Value Filler', description='Fill with mean value', cleaner='mean', cleaner_id=68, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with median value', cleaner='median', cleaner_id=69, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with most frequent value', cleaner='mode', cleaner_id=70, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with previous value', cleaner='ffill', cleaner_id=71, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with next value', cleaner='bfill', cleaner_id=72, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Delete the row', cleaner='delete', cleaner_id=73, activate=True, data=None)]),
 ScanResult(row=11, col=num5, message='Outlier detected in column 'num5' at row 12', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Outlier Handler', description='Delete the outlier', cleaner='delete', cleaner_id=0, activate=True, data=None), ScanResultAction(title='Outlier Handler', description='Keep the outlier', cleaner='keep', cleaner_id=1, activate=True, data=None)]),
 ScanResult(row=0, col=num1, message='Target value '51' found in row 1, column 'num1'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Handle '{target}'', description='Handle the '{target}' value', cleaner='handle_target', cleaner_id=None, activate=True, data=None)]),
 ScanResult(row=10, col=num1, message='Target value '51' found in row 11, column 'num1'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Handle '{target}'', description='Handle the '{target}' value', cleaner='handle_target', cleaner_id=None, activate=True, data=None)]),
 ScanResult(row=20, col=num1, message='Target value '51' found in row 21, column 'num1'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Handle '{target}'', description='Handle the '{target}' value', cleaner='handle_target', cleaner_id=None, activate=True, data=None)])]

In [16]:
import random

def choose_one_action_per_scan_result(scan_results):
    for sr in scan_results:
        if sr.actions:
            chosen_action = random.choice(sr.actions)
            for action in sr.actions:
                action.activate = False
            chosen_action.activate = True
            sr.actions = [chosen_action]
    return scan_results


chosen_scan_results = choose_one_action_per_scan_result(scan_results)

chosen_scan_results

[ScanResult(row=10, col=-1, message='Row 11 is duplicated', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Duplication Remover', description='Keep the duplicated rows', cleaner='keep', cleaner_id=1, activate=True, data=None)]),
 ScanResult(row=20, col=-1, message='Row 21 is duplicated', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Duplication Remover', description='Keep the duplicated rows', cleaner='keep', cleaner_id=3, activate=True, data=None)]),
 ScanResult(row=1, col=num3, message='Missing value in row 2, column 'num3'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Missing Value Filler', description='Fill with previous value', cleaner='ffill', cleaner_id=3, activate=True, data=None)]),
 ScanResult(row=5, col=num2, message='Missing value in row 6, column 'num2'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Missing Value Filler', description='Fill with most frequent value', cleaner='mode', cleaner_id=8, activate=True, data=None)]),
 ScanResult(row=5, col=num3, message='Missing value in row 6, column 'num3'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Missing Value Filler', description='Fill with mean value', cleaner='mean', cleaner_id=12, activate=True, data=None)]),
 ScanResult(row=19, col=text, message='Missing value in row 20, column 'text'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Missing Value Filler', description='Fill with previous value', cleaner='ffill', cleaner_id=19, activate=True, data=None)]),
 ScanResult(row=21, col=num2, message='Missing value in row 22, column 'num2'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Missing Value Filler', description='Fill with next value', cleaner='bfill', cleaner_id=26, activate=True, data=None)]),
 ScanResult(row=24, col=text, message='Missing value in row 25, column 'text'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Missing Value Filler', description='Delete the row', cleaner='delete', cleaner_id=31, activate=True, data=None)]),
 ScanResult(row=25, col=num2, message='Missing value in row 26, column 'num2'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Missing Value Filler', description='Delete the row', cleaner='delete', cleaner_id=37, activate=True, data=None)]),
 ScanResult(row=28, col=num3, message='Missing value in row 29, column 'num3'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Missing Value Filler', description='Fill with mean value', cleaner='mean', cleaner_id=38, activate=True, data=None)]),
 ScanResult(row=31, col=text, message='Missing value in row 32, column 'text'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Missing Value Filler', description='Delete the row', cleaner='delete', cleaner_id=47, activate=True, data=None)]),
 ScanResult(row=36, col=text, message='Missing value in row 37, column 'text'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Missing Value Filler', description='Fill with most frequent value', cleaner='mode', cleaner_id=48, activate=True, data=None)]),
 ScanResult(row=40, col=text, message='Missing value in row 41, column 'text'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Missing Value Filler', description='Fill with previous value', cleaner='ffill', cleaner_id=53, activate=True, data=None)]),
 ScanResult(row=41, col=num3, message='Missing value in row 42, column 'num3'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Missing Value Filler', description='Fill with most frequent value', cleaner='mode', cleaner_id=58, activate=True, data=None)]),
 ScanResult(row=42, col=num2, message='Missing value in row 43, column 'num2'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Missing Value Filler', description='Fill with previous value', cleaner='ffill', cleaner_id=65, activate=True, data=None)]),
 ScanResult(row=44, col=num3, message='Missing value in row 45, column 'num3'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Missing Value Filler', description='Fill with previous value', cleaner='ffill', cleaner_id=71, activate=True, data=None)]),
 ScanResult(row=11, col=num5, message='Outlier detected in column 'num5' at row 12', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Outlier Handler', description='Delete the outlier', cleaner='delete', cleaner_id=0, activate=True, data=None)]),
 ScanResult(row=0, col=num1, message='Target value '51' found in row 1, column 'num1'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Handle '{target}'', description='Handle the '{target}' value', cleaner='handle_target', cleaner_id=None, activate=True, data=None)]),
 ScanResult(row=10, col=num1, message='Target value '51' found in row 11, column 'num1'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Handle '{target}'', description='Handle the '{target}' value', cleaner='handle_target', cleaner_id=None, activate=True, data=None)]),
 ScanResult(row=20, col=num1, message='Target value '51' found in row 21, column 'num1'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Handle '{target}'', description='Handle the '{target}' value', cleaner='handle_target', cleaner_id=None, activate=True, data=None)])]

In [17]:
df1 = apply_scan_results(df1, chosen_scan_results)
df1

,num1,num2,cat1,cat2,num3,num4,text,bool,num5,cat3
0,51,-20.267196,cherry,red,33.606777,98,Sample 0,True,0.291044,Y
1,92,11.194236,banana,red,33.606777,152,Sample 1,False,-5.714851,Y
2,14,7.791926,cherry,red,11.881877,92,Sample 2,True,1.788937,X
3,71,-11.010978,apple,blue,36.410817,145,Sample 3,False,2.803923,X
4,60,11.302282,apple,green,18.389157,127,Sample 4,True,5.415256,X
5,20,-20.267196,banana,red,25.080387,109,Sample 5,False,5.269010,X
6,82,-3.864730,cherry,red,31.676486,81,Sample 6,False,-6.888347,X
7,86,-11.587702,cherry,red,26.788734,193,Sample 7,False,-4.689125,Z
8,74,5.661128,banana,blue,4.514489,53,Sample 8,True,2.575176,Z
9,74,-7.044535,cherry,blue,41.765125,162,Sample 9,False,2.568930,X
10,51,-20.267196,cherry,red,33.606777,98,Sample 0,True,0.291044,Y
11,23,-4.614657,cherry,red,2.038757,160,Sample 12,True,2.854453,Z
12,2,0.666573,cherry,green,29.544647,67,Sample 13,False,5.677828,Z
13,21,-1.762857,banana,red,33.878218,32,Sample 14,True,4.770009,Y
14,52,12.008928,banana,red,0.829391,141,Sample 15,True,3.256956,Z
15,1,6.983989,apple,blue,25.604653,20,Sample 16,False,-1.576346,X
16,87,-1.716288,cherry,green,11.324789,47,Sample 17,True,3.794846,Y
17,29,-9.071866,cherry,blue,32.258640,147,Sample 18,True,-3.864126,X
18,37,11.886257,cherry,blue,8.718321,127,Sample 18,False,-1.184093,X
19,51,-20.267196,cherry,red,33.606777,98,Sample 0,True,0.291044,Y
20,63,2.634860,apple,red,19.336767,134,Sample 21,True,0.409371,X
21,59,2.634860,banana,red,46.836499,194,Sample 22,True,11.573293,Z
22,20,16.417711,apple,green,6.876047,144,Sample 23,False,-9.336326,X
23,57,-15.099573,apple,green,46.234681,175,Sample 26,True,-2.359659,Y
24,21,7.215025,cherry,blue,43.866968,186,Sample 27,True,5.444753,X
25,88,-8.434199,cherry,green,25.690026,114,Sample 28,True,0.321400,Y
26,48,-5.133254,apple,blue,32.999202,118,Sample 29,False,-5.388724,Y
27,90,-0.435368,apple,red,40.861110,21,Sample 30,True,-3.576519,X
28,41,-15.630668,cherry,red,26.482529,37,Sample 32,False,-3.651833,X
29,91,-7.956310,cherry,red,12.092615,108,Sample 33,True,1.082293,Y
30,59,9.305844,banana,blue,4.655138,50,Sample 34,False,0.227859,Y
31,79,6.777674,banana,red,44.860788,181,Sample 35,False,-3.258002,X
32,14,6.984403,banana,green,45.020903,7,Sample 0,True,10.719720,Z
33,61,1.736021,apple,green,31.655073,26,Sample 37,False,3.169595,Y
34,61,6.622845,banana,green,16.951490,26,Sample 38,True,-10.125713,Y
35,46,2.411222,apple,blue,17.460479,20,Sample 39,False,0.932272,Y
36,61,-1.682051,apple,red,36.297784,29,Sample 43,False,-3.308932,X
37,50,11.647686,banana,red,33.606777,96,Sample 41,True,4.262167,Y
38,54,12.334968,banana,red,44.354321,27,Sample 42,False,-3.962604,Z
39,63,-7.696678,banana,blue,38.993777,110,Sample 43,False,-0.573682,Y
40,2,12.121723,cherry,green,44.927709,191,Sample 44,False,2.524936,Y
41,50,12.334968,banana,green,4.206998,196,Sample 45,False,4.328776,Z
42,6,-15.741553,cherry,red,8.081436,60,Sample 46,False,-6.001482,Y
43,20,6.379529,apple,green,44.927709,47,Sample 47,True,-1.672506,X
44,72,-20.444230,cherry,green,30.321453,146,Sample 48,False,-2.374727,X
45,38,10.694809,banana,blue,0.459853,3,Sample 49,True,-3.266646,X

In [ ]:
from autoML_cleaning import *

df2 = auto_ML_cleaning(df2, 'cat1')
df2

,num1,num2,cat1,cat2,num3,num4,text,num5,cat3,bool
0,50,11.647686,banana,red,NaN,96,Sample 41,4.262167,Y,True
1,87,-1.716288,cherry,green,11.324789,47,Sample 17,3.794846,Y,True
2,91,-7.956310,cherry,red,12.092614,108,Sample 33,1.082293,Y,True
3,46,2.411222,apple,blue,17.460478,20,Sample 39,0.932272,Y,False
4,75,NaN,cherry,green,5.673676,32,Sample 25,-8.063580,Y,False
5,20,NaN,banana,red,NaN,109,Sample 5,5.269010,X,False
6,74,-7.044535,cherry,blue,41.765125,162,Sample 9,2.568930,X,False
7,74,5.661128,banana,blue,4.514489,53,Sample 8,2.575176,Z,True
8,37,11.886257,cherry,blue,8.718322,127,NaN,-1.184093,X,False
9,79,6.777674,banana,red,44.860786,181,Sample 35,-3.258002,X,False
10,63,-7.696678,banana,blue,38.993778,110,Sample 43,-0.573682,Y,False
11,14,7.791926,cherry,red,11.881877,92,Sample 2,1.788937,X,True
12,23,-4.614657,cherry,red,2.038757,160,Sample 12,2.854453,Z,True
13,21,7.215024,cherry,blue,43.866966,186,Sample 27,5.444753,X,True
14,1,6.983989,apple,blue,25.604652,20,Sample 16,-1.576346,X,False
15,60,11.302282,apple,green,18.389156,127,Sample 4,5.415256,X,True
16,92,11.194236,banana,red,NaN,152,Sample 1,-5.714851,Y,False
17,59,2.634861,banana,red,46.836498,194,Sample 22,11.573293,Z,True
18,71,-11.010978,apple,blue,36.410816,145,Sample 3,2.803923,X,False
19,48,-5.133254,apple,blue,32.999203,118,Sample 29,-5.388724,Y,False
20,41,-15.630668,cherry,red,26.482529,37,Sample 32,-3.651833,X,False
21,86,-11.587703,cherry,red,26.788734,193,Sample 7,-4.689125,Z,False
22,21,-1.762857,banana,red,33.878220,32,Sample 14,4.770009,Y,True
23,61,1.736021,apple,green,31.655073,26,Sample 37,3.169595,Y,False
24,51,-20.267197,cherry,red,33.606777,98,Sample 0,0.291044,Y,True
25,61,6.622845,banana,green,16.951490,26,Sample 38,-10.125713,Y,True
26,50,12.334968,banana,green,4.206998,196,Sample 45,4.328776,Z,False
27,29,-9.071866,cherry,blue,32.258640,147,Sample 18,-3.864126,X,True
28,14,6.984403,banana,green,45.020905,7,NaN,10.719721,Z,True
29,82,-3.864729,cherry,red,31.676485,81,Sample 6,-6.888347,X,False
30,52,12.008927,banana,red,0.829391,141,Sample 15,3.256956,Z,True
31,57,-15.099573,apple,green,46.234680,175,Sample 26,-2.359659,Y,True
32,6,-15.741553,cherry,red,8.081436,60,Sample 46,-6.001482,Y,False
33,32,4.608163,cherry,red,17.053318,127,NaN,3.431301,Y,True
34,63,NaN,apple,red,19.336767,134,Sample 21,0.409371,X,True
35,2,12.121723,cherry,green,NaN,191,Sample 44,2.524936,Y,False
36,72,-20.444231,cherry,green,30.321453,146,Sample 48,-2.374727,X,False
37,20,6.379529,apple,green,44.927708,47,Sample 47,-1.672506,X,True
38,38,10.694809,banana,blue,0.459853,3,Sample 49,-3.266646,X,True
39,20,16.417711,apple,green,6.876047,144,Sample 23,-9.336326,X,False
40,59,9.305844,banana,blue,4.655138,50,Sample 34,0.227859,Y,False
41,88,-8.434199,cherry,green,NaN,114,Sample 28,0.321400,Y,True
42,54,NaN,banana,red,44.354321,27,Sample 42,-3.962604,Z,False
43,99,-3.531167,apple,blue,9.325926,168,Sample 11,19.263657,X,False
44,2,0.666573,cherry,green,29.544647,67,Sample 13,5.677828,Z,False
45,90,-0.435368,apple,red,40.861111,21,Sample 30,-3.576519,X,True
46,61,-1.682051,apple,red,36.297783,29,NaN,-3.308932,X,False
47,58,-2.753009,cherry,red,27.760040,157,NaN,3.397989,Z,True