In [6]:
import pandas as pd
import numpy as np
from ScanResult import *
from data_scan import *
from data_clean_manual import *

In [7]:
np.random.seed(42)
rows = 20

# Create sample data with 10 columns.
data = {
    "Name": [
        "John Smith", "Emma Johnson", "Emma Johnson", "Robert Brown", "Olivia Davis",
        "Michael Wilson", "Isabella Miller", "William Taylor", "Sophia Anderson",
        "James Thomas", "Ava Jackson"
    ],
    "Age": [34, 28, 28, 45, 23, 54, 29, 38, 32, 41, 26],
    "Gender": [
        "Male", "Female", "Female", "Male", "Female",
        "Male", "Female", "Male", "Female", "Male", "Female"
    ],
    "Salary": [
        58324.75, 74920.3, 74920.3, 95234.2, 60540,
        71032.8, None, 80340.1, 55678.9, 98760.25, 1000067200
    ]
}
df1 = pd.DataFrame(data)

df1

               Name  Age  Gender        Salary
0        John Smith   34    Male  5.832475e+04
1      Emma Johnson   28  Female  7.492030e+04
2      Emma Johnson   28  Female  7.492030e+04
3      Robert Brown   45    Male  9.523420e+04
4      Olivia Davis   23  Female  6.054000e+04
5    Michael Wilson   54    Male  7.103280e+04
6   Isabella Miller   29  Female           NaN
7    William Taylor   38    Male  8.034010e+04
8   Sophia Anderson   32  Female  5.567890e+04
9      James Thomas   41    Male  9.876025e+04
10      Ava Jackson   26  Female  1.000067e+09

In [8]:
#all_null_cols = df1.columns[df1.isnull().all()]
#df1.drop(columns=all_null_cols, inplace=True)
scan_results = []
scan_results.extend(scan_df_for_duplicates(df1))
scan_results.extend(scan_df_for_outliers(df1))
scan_results.extend(scan_df_for_missing(df1))
scan_results.extend(scan_df_for_categorical(df1))

scan_results

[ScanResult(row=2, col=-1, message='Row 3 is duplicated', action_type=SRActionType.ONE_MANDATORY, actions=[ScanResultAction(title='Duplication Remover', description='Remove the duplicated rows', cleaner='clean_df_for_duplicates', cleaner_id=None, activate=True, data=None)]),
 ScanResult(row=10, col=3, message='Outlier detected in column 'Salary' at row 11', action_type=SRActionType.ONE_MANDATORY, actions=[ScanResultAction(title='Outlier Handler', description='Delete the outlier', cleaner='clean_df_for_outlier', cleaner_id=None, activate=True, data=None)]),
 ScanResult(row=6, col=3, message='Missing value in row 7, column 'Salary'', action_type=SRActionType.ONE_MANDATORY, actions=[ScanResultAction(title='Missing Value Filler', description='Fill with mean value', cleaner='fill_with_mean', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with median value', cleaner='fill_with_median', cleaner_id=None, activate=False, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with most frequent value', cleaner='fill_with_mode', cleaner_id=None, activate=False, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with previous value', cleaner='fill_with_ffill', cleaner_id=None, activate=False, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with next value', cleaner='fill_with_bfill', cleaner_id=None, activate=False, data=None), ScanResultAction(title='Missing Value Filler', description='Delete the row', cleaner='delete_missing_rows', cleaner_id=None, activate=False, data=None)]),
 ScanResult(row=-1, col=Name, message='Categorical feature 'Name' detected with 10 categories: John Smith, Emma Johnson, Robert Brown, Olivia Davis, Michael Wilson, Isabella Miller, William Taylor, Sophia Anderson, James Thomas, Ava Jackson', action_type=SRActionType.ONE_MANDATORY, actions=[ScanResultAction(title='Categorical Encoder', description='Apply one-hot encoding', cleaner='clean_df_cat_one_hot', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Categorical Encoder', description='Apply label encoding', cleaner='clean_df_cat_label_encoding', cleaner_id=None, activate=False, data=None), ScanResultAction(title='Categorical Encoder', description='Drop the column', cleaner='clean_df_cat_drop', cleaner_id=None, activate=False, data=None)]),
 ScanResult(row=-1, col=Gender, message='Categorical feature 'Gender' detected with 2 categories: Male, Female', action_type=SRActionType.ONE_MANDATORY, actions=[ScanResultAction(title='Categorical Encoder', description='Apply one-hot encoding', cleaner='clean_df_cat_one_hot', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Categorical Encoder', description='Apply label encoding', cleaner='clean_df_cat_label_encoding', cleaner_id=None, activate=False, data=None), ScanResultAction(title='Categorical Encoder', description='Drop the column', cleaner='clean_df_cat_drop', cleaner_id=None, activate=False, data=None)])]

In [9]:
for scan_result in scan_results:
    print(f"\n")
    for action in scan_result.actions:
        function_name = action.cleaner
        if function_name in globals() and action.activate == True:
            df1 = globals()[function_name](scan_result, df1)
            print(f"{df1.to_string()} {function_name}\n")

               Name  Age  Gender        Salary
0        John Smith   34    Male  5.832475e+04
1      Emma Johnson   28  Female  7.492030e+04
3      Robert Brown   45    Male  9.523420e+04
4      Olivia Davis   23  Female  6.054000e+04
5    Michael Wilson   54    Male  7.103280e+04
6   Isabella Miller   29  Female           NaN
7    William Taylor   38    Male  8.034010e+04
8   Sophia Anderson   32  Female  5.567890e+04
9      James Thomas   41    Male  9.876025e+04
10      Ava Jackson   26  Female  1.000067e+09 clean_df_for_duplicates



              Name  Age  Gender    Salary
0       John Smith   34    Male  58324.75
1     Emma Johnson   28  Female  74920.30
3     Robert Brown   45    Male  95234.20
4     Olivia Davis   23  Female  60540.00
5   Michael Wilson   54    Male  71032.80
6  Isabella Miller   29  Female       NaN
7   William Taylor   38    Male  80340.10
8  Sophia Anderson   32  Female  55678.90
9     James Thomas   41    Male  98760.25 clean_df_for_outlier



              Name  Age  Gender      Salary
0       John Smith   34    Male  58324.7500
1     Emma Johnson   28  Female  74920.3000
3     Robert Brown   45    Male  95234.2000
4     Olivia Davis   23  Female  60540.0000
5   Michael Wilson   54    Male  71032.8000
6  Isabella Miller   29  Female  74353.9125
7   William Taylor   38    Male  80340.1000
8  Sophia Anderson   32  Female  55678.9000
9     James Thomas   41    Male  98760.2500 fill_with_mean



   Age  Gender      Salary  Name_Emma Johnson  Name_Isabella Miller  Name_James Thomas  Name_John Smith  Name_Michael Wilson  Name_Olivia Davis  Name_Robert Brown  Name_Sophia Anderson  Name_William Taylor
0   34    Male  58324.7500                  0                     0                  0                1                    0                  0                  0                     0                    0
1   28  Female  74920.3000                  1                     0                  0                0                    0                  0                  0                     0                    0
3   45    Male  95234.2000                  0                     0                  0                0                    0                  0                  1                     0                    0
4   23  Female  60540.0000                  0                     0                  0                0                    0                  1                  0                     0                    0
5   54    Male  71032.8000                  0                     0                  0                0                    1                  0                  0                     0                    0
6   29  Female  74353.9125                  0                     1                  0                0                    0                  0                  0                     0                    0
7   38    Male  80340.1000                  0                     0                  0                0                    0                  0                  0                     0                    1
8   32  Female  55678.9000                  0                     0                  0                0                    0                  0                  0                     1                    0
9   41    Male  98760.2500                  0                     0                  1                0                    0                  0                  0                     0                    0 clean_df_cat_one_hot



   Age      Salary  Name_Emma Johnson  Name_Isabella Miller  Name_James Thomas  Name_John Smith  Name_Michael Wilson  Name_Olivia Davis  Name_Robert Brown  Name_Sophia Anderson  Name_William Taylor  Gender_Female  Gender_Male
0   34  58324.7500                  0                     0                  0                1                    0                  0                  0                     0                    0              0            1
1   28  74920.3000                  1                     0                  0                0                    0                  0                  0                     0                    0              1            0
3   45  95234.2000                  0                     0                  0                0                    0                  0                  1                     0                    0              0            1
4   23  60540.0000                  0                     0                  0                0                    0                  1                  0                     0                    0              1            0
5   54  71032.8000                  0                     0                  0                0                    1                  0                  0                     0                    0              0            1
6   29  74353.9125                  0                     1                  0                0                    0                  0                  0                     0                    0              1            0
7   38  80340.1000                  0                     0                  0                0                    0                  0                  0                     0                    1              0            1
8   32  55678.9000                  0                     0                  0                0                    0                  0                  0                     1                    0              1            0
9   41  98760.2500                  0                     0                  1                0                    0                  0                  0                     0                    0              0            1 clean_df_cat_one_hot

d:\SEGP-G6\notebooks\data_clean_manual.py:91: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(index=scan_result.row, inplace=True)
d:\SEGP-G6\notebooks\data_clean_manual.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col_name] = pd.to_numeric(df[col_name], errors='coerce')
d:\SEGP-G6\notebooks\data_clean_manual.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col_name].fillna(df[col_name].mean(), inplace=True)

In [10]:
from data_clean_auto import *

data = {
    "Name": [
        "John Smith", "Emma Johnson", "Emma Johnson", "Robert Brown", "Olivia Davis",
        "Michael Wilson", "Isabella Miller", "William Taylor", "Sophia Anderson",
        "James Thomas", "Ava Jackson"
    ],
    "Age": [34, 28, 28, 45, 23, 54, 29, 38, 32, 41, 26],
    "Gender": [
        "Male", "Female", "Female", "Male", "Female",
        "Male", "Female", "Male", "Female", "Male", "Female"
    ],
    "Salary": [
        58324.75, 74920.3, 74920.3, 95234.2, 60540,
        71032.8, None, 80340.1, 55678.9, 98760.25, 1000067200
    ]
}
df2 = pd.DataFrame(data)

df2 = clean_data(df2)
df2

    Age        Salary  Gender_male
0  34.0  5.832475e+04            1
1  28.0  7.492030e+04            0
2  45.0  9.523420e+04            1
3  23.0  6.054000e+04            0
4  54.0  7.103280e+04            1
5  29.0  1.111847e+08            0
6  38.0  8.034010e+04            1
7  32.0  5.567890e+04            0
8  41.0  9.876025e+04            1