In [2]:
import pandas as pd
import numpy as np
from ScanResult import *
from data_scan import *
from data_clean_manual import *

In [3]:
np.random.seed(42)
rows = 20

# Create sample data with 10 columns.
data = {
    "num1": np.random.randint(0, 100, size=rows),
    "num2": np.random.randn(rows) * 10,
    "cat1": np.random.choice(["apple", "banana", "cherry"], size=rows),
    "cat2": np.random.choice(["red", "green", "blue"], size=rows),
    "num3": np.random.uniform(0, 50, size=rows),
    "num4": np.random.randint(0, 200, size=rows),
    "text": [f"Sample {i}" for i in range(rows)],
    "bool": np.random.choice([True, False], size=rows),
    "num5": np.random.randn(rows) * 5,
    "cat3": np.random.choice(["X", "Y", "Z"], size=rows),
    "cat4": ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't'],
    "empty_col": [np.nan] * 20 ,
    "cat5": np.random.choice(["X"], size=rows),
}
df = pd.DataFrame(data)

for col in ["num2", "num3", "text", "bool"]:
    missing_indices = np.random.choice(df.index, size=3, replace=False)
    df.loc[missing_indices, col] = np.nan

df.loc[10] = df.loc[0]
df.loc[20] = df.loc[0]

df1 = df.copy()
df2 = df.copy()
df2

C:\Users\zhiha\AppData\Local\Temp\ipykernel_25816\2203771725.py:24: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'nan' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  df.loc[missing_indices, col] = np.nan

,num1,num2,cat1,cat2,num3,num4,text,bool,num5,cat3,cat4,empty_col,cat5
0,51,14.623781,cherry,green,0.781820,34,Sample 0,False,-3.051610,X,a,NaN,X
1,92,15.387150,apple,blue,21.170074,192,Sample 1,False,-1.580829,X,b,NaN,X
2,14,NaN,cherry,blue,19.744076,100,Sample 2,True,-7.412121,Y,c,NaN,X
3,71,6.034412,cherry,green,14.674409,174,NaN,True,-1.144238,X,d,NaN,X
4,60,-2.510440,banana,blue,0.703991,130,NaN,True,4.813206,Y,e,NaN,X
5,20,-1.638671,apple,red,9.942120,0,Sample 5,True,-1.048462,Y,f,NaN,X
6,82,-14.763297,banana,green,35.567098,4,Sample 6,True,-3.870215,Z,g,NaN,X
7,86,14.869810,banana,red,NaN,141,Sample 7,NaN,-1.798891,Y,h,NaN,X
8,74,NaN,banana,red,30.297999,102,Sample 8,True,3.620416,Z,i,NaN,X
9,74,3.555513,banana,green,46.315044,26,Sample 9,False,-1.278823,X,j,NaN,X
10,51,14.623781,cherry,green,0.781820,34,Sample 0,False,-3.051610,X,a,NaN,X
11,99,8.324619,banana,red,45.747984,14,Sample 11,False,-6.556621,X,l,NaN,X
12,23,-2.933991,banana,green,NaN,89,Sample 12,True,-4.351525,X,m,NaN,X
13,2,-0.298386,apple,red,22.472534,41,NaN,True,-2.533216,Z,n,NaN,X
14,21,0.951258,cherry,red,4.770506,123,Sample 14,NaN,-6.549753,X,o,NaN,X
15,52,NaN,banana,red,18.540913,178,Sample 15,False,14.718317,Y,p,NaN,X
16,1,-1.402185,banana,red,NaN,62,Sample 16,False,-5.481329,Y,q,NaN,X
17,87,-0.331934,banana,blue,33.296118,95,Sample 17,NaN,4.574422,Y,r,NaN,X
18,29,-7.490765,banana,red,29.564889,51,Sample 18,False,-3.330303,Z,s,NaN,X
19,37,-7.783820,banana,red,13.736090,95,Sample 19,True,-2.568937,X,t,NaN,X
20,51,14.623781,cherry,green,0.781820,34,Sample 0,False,-3.051610,X,a,NaN,X

In [4]:
all_null_cols = df1.columns[df1.isnull().all()]
df1.drop(columns=all_null_cols, inplace=True)
scan_results = []
scan_results.extend(scan_df_for_duplicates(df1))
scan_results.extend(scan_df_for_missing(df1))
scan_results.extend(scan_df_for_outliers(df1))
scan_results.extend(scan_df_for_categorical(df1))

scan_results

[ScanResult(row=10, col=-1, message='Row 11 is duplicated', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Duplication Remover', description='Remove the duplicated rows', cleaner='clean_df_for_duplicates', cleaner_id=None, activate=True, data=None)]),
 ScanResult(row=20, col=-1, message='Row 21 is duplicated', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Duplication Remover', description='Remove the duplicated rows', cleaner='clean_df_for_duplicates', cleaner_id=None, activate=True, data=None)]),
 ScanResult(row=2, col=num2, message='Missing value in row 3, column 'num2'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Missing Value Filler', description='Fill with mean value', cleaner='fill_with_mean', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with median value', cleaner='fill_with_median', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with most frequent value', cleaner='fill_with_mode', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with previous value', cleaner='fill_with_ffill', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with next value', cleaner='fill_with_bfill', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Delete the row', cleaner='delete_missing_rows', cleaner_id=None, activate=True, data=None)]),
 ScanResult(row=3, col=text, message='Missing value in row 4, column 'text'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Missing Value Filler', description='Fill with most frequent value', cleaner='fill_with_mode', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with previous value', cleaner='fill_with_ffill', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with next value', cleaner='fill_with_bfill', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Delete the row', cleaner='delete_missing_rows', cleaner_id=None, activate=True, data=None)]),
 ScanResult(row=4, col=text, message='Missing value in row 5, column 'text'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Missing Value Filler', description='Fill with most frequent value', cleaner='fill_with_mode', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with previous value', cleaner='fill_with_ffill', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with next value', cleaner='fill_with_bfill', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Delete the row', cleaner='delete_missing_rows', cleaner_id=None, activate=True, data=None)]),
 ScanResult(row=7, col=num3, message='Missing value in row 8, column 'num3'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Missing Value Filler', description='Fill with mean value', cleaner='fill_with_mean', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with median value', cleaner='fill_with_median', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with most frequent value', cleaner='fill_with_mode', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with previous value', cleaner='fill_with_ffill', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with next value', cleaner='fill_with_bfill', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Delete the row', cleaner='delete_missing_rows', cleaner_id=None, activate=True, data=None)]),
 ScanResult(row=7, col=bool, message='Missing value in row 8, column 'bool'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Missing Value Filler', description='Fill with most frequent value', cleaner='fill_with_mode', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with previous value', cleaner='fill_with_ffill', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with next value', cleaner='fill_with_bfill', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Delete the row', cleaner='delete_missing_rows', cleaner_id=None, activate=True, data=None)]),
 ScanResult(row=8, col=num2, message='Missing value in row 9, column 'num2'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Missing Value Filler', description='Fill with mean value', cleaner='fill_with_mean', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with median value', cleaner='fill_with_median', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with most frequent value', cleaner='fill_with_mode', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with previous value', cleaner='fill_with_ffill', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with next value', cleaner='fill_with_bfill', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Delete the row', cleaner='delete_missing_rows', cleaner_id=None, activate=True, data=None)]),
 ScanResult(row=12, col=num3, message='Missing value in row 13, column 'num3'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Missing Value Filler', description='Fill with mean value', cleaner='fill_with_mean', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with median value', cleaner='fill_with_median', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with most frequent value', cleaner='fill_with_mode', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with previous value', cleaner='fill_with_ffill', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with next value', cleaner='fill_with_bfill', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Delete the row', cleaner='delete_missing_rows', cleaner_id=None, activate=True, data=None)]),
 ScanResult(row=13, col=text, message='Missing value in row 14, column 'text'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Missing Value Filler', description='Fill with most frequent value', cleaner='fill_with_mode', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with previous value', cleaner='fill_with_ffill', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with next value', cleaner='fill_with_bfill', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Delete the row', cleaner='delete_missing_rows', cleaner_id=None, activate=True, data=None)]),
 ScanResult(row=14, col=bool, message='Missing value in row 15, column 'bool'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Missing Value Filler', description='Fill with most frequent value', cleaner='fill_with_mode', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with previous value', cleaner='fill_with_ffill', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with next value', cleaner='fill_with_bfill', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Delete the row', cleaner='delete_missing_rows', cleaner_id=None, activate=True, data=None)]),
 ScanResult(row=15, col=num2, message='Missing value in row 16, column 'num2'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Missing Value Filler', description='Fill with mean value', cleaner='fill_with_mean', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with median value', cleaner='fill_with_median', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with most frequent value', cleaner='fill_with_mode', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with previous value', cleaner='fill_with_ffill', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with next value', cleaner='fill_with_bfill', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Delete the row', cleaner='delete_missing_rows', cleaner_id=None, activate=True, data=None)]),
 ScanResult(row=16, col=num3, message='Missing value in row 17, column 'num3'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Missing Value Filler', description='Fill with mean value', cleaner='fill_with_mean', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with median value', cleaner='fill_with_median', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with most frequent value', cleaner='fill_with_mode', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with previous value', cleaner='fill_with_ffill', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with next value', cleaner='fill_with_bfill', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Delete the row', cleaner='delete_missing_rows', cleaner_id=None, activate=True, data=None)]),
 ScanResult(row=17, col=bool, message='Missing value in row 18, column 'bool'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Missing Value Filler', description='Fill with most frequent value', cleaner='fill_with_mode', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with previous value', cleaner='fill_with_ffill', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Fill with next value', cleaner='fill_with_bfill', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Missing Value Filler', description='Delete the row', cleaner='delete_missing_rows', cleaner_id=None, activate=True, data=None)]),
 ScanResult(row=4, col=num5, message='Outlier detected in column 'num5' at row 5', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Outlier Handler', description='Delete the outlier', cleaner='delete_outlier', cleaner_id=None, activate=True, data=None)]),
 ScanResult(row=8, col=num5, message='Outlier detected in column 'num5' at row 9', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Outlier Handler', description='Delete the outlier', cleaner='delete_outlier', cleaner_id=None, activate=True, data=None)]),
 ScanResult(row=15, col=num5, message='Outlier detected in column 'num5' at row 16', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Outlier Handler', description='Delete the outlier', cleaner='delete_outlier', cleaner_id=None, activate=True, data=None)]),
 ScanResult(row=17, col=num5, message='Outlier detected in column 'num5' at row 18', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Outlier Handler', description='Delete the outlier', cleaner='delete_outlier', cleaner_id=None, activate=True, data=None)]),
 ScanResult(row=-1, col=cat1, message='Categorical feature 'cat1' detected with 3 categories: cherry, apple, banana', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Categorical Encoder', description='Apply one-hot encoding', cleaner='one_hot', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Categorical Encoder', description='Apply label encoding', cleaner='label_encoding', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Categorical Encoder', description='Drop the column', cleaner='drop', cleaner_id=None, activate=True, data=None)]),
 ScanResult(row=-1, col=cat2, message='Categorical feature 'cat2' detected with 3 categories: green, blue, red', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Categorical Encoder', description='Apply one-hot encoding', cleaner='one_hot', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Categorical Encoder', description='Apply label encoding', cleaner='label_encoding', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Categorical Encoder', description='Drop the column', cleaner='drop', cleaner_id=None, activate=True, data=None)]),
 ScanResult(row=-1, col=text, message='Categorical feature 'text' detected with 16 categories: Sample 0, Sample 1, Sample 2, Sample 5, Sample 6, Sample 7, Sample 8, Sample 9, Sample 11, Sample 12... (Total 16 categories)', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Categorical Encoder', description='Apply one-hot encoding', cleaner='one_hot', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Categorical Encoder', description='Apply label encoding', cleaner='label_encoding', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Categorical Encoder', description='Drop the column', cleaner='drop', cleaner_id=None, activate=True, data=None)]),
 ScanResult(row=-1, col=bool, message='Categorical feature 'bool' detected with 2 categories: False, True', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Categorical Encoder', description='Apply one-hot encoding', cleaner='one_hot', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Categorical Encoder', description='Apply label encoding', cleaner='label_encoding', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Categorical Encoder', description='Drop the column', cleaner='drop', cleaner_id=None, activate=True, data=None)]),
 ScanResult(row=-1, col=cat3, message='Categorical feature 'cat3' detected with 3 categories: X, Y, Z', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Categorical Encoder', description='Apply one-hot encoding', cleaner='one_hot', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Categorical Encoder', description='Apply label encoding', cleaner='label_encoding', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Categorical Encoder', description='Drop the column', cleaner='drop', cleaner_id=None, activate=True, data=None)]),
 ScanResult(row=-1, col=cat4, message='Categorical feature 'cat4' detected with 19 categories: a, b, c, d, e, f, g, h, i, j... (Total 19 categories)', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Categorical Encoder', description='Apply one-hot encoding', cleaner='one_hot', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Categorical Encoder', description='Apply label encoding', cleaner='label_encoding', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Categorical Encoder', description='Drop the column', cleaner='drop', cleaner_id=None, activate=True, data=None)]),
 ScanResult(row=-1, col=cat5, message='Categorical feature 'cat5' detected with 1 categories: X', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Categorical Encoder', description='Apply one-hot encoding', cleaner='one_hot', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Categorical Encoder', description='Apply label encoding', cleaner='label_encoding', cleaner_id=None, activate=True, data=None), ScanResultAction(title='Categorical Encoder', description='Drop the column', cleaner='drop', cleaner_id=None, activate=True, data=None)])]

In [5]:
import random

def choose_one_action_per_scan_result(scan_results):
    for sr in scan_results:
        if sr.actions:
            chosen_action = random.choice(sr.actions)
            for action in sr.actions:
                action.activate = False
            chosen_action.activate = True
            sr.actions = [chosen_action]
    return scan_results


chosen_scan_results = choose_one_action_per_scan_result(scan_results)

chosen_scan_results

[ScanResult(row=10, col=-1, message='Row 11 is duplicated', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Duplication Remover', description='Remove the duplicated rows', cleaner='clean_df_for_duplicates', cleaner_id=None, activate=True, data=None)]),
 ScanResult(row=20, col=-1, message='Row 21 is duplicated', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Duplication Remover', description='Remove the duplicated rows', cleaner='clean_df_for_duplicates', cleaner_id=None, activate=True, data=None)]),
 ScanResult(row=2, col=num2, message='Missing value in row 3, column 'num2'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Missing Value Filler', description='Delete the row', cleaner='delete_missing_rows', cleaner_id=None, activate=True, data=None)]),
 ScanResult(row=3, col=text, message='Missing value in row 4, column 'text'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Missing Value Filler', description='Fill with next value', cleaner='fill_with_bfill', cleaner_id=None, activate=True, data=None)]),
 ScanResult(row=4, col=text, message='Missing value in row 5, column 'text'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Missing Value Filler', description='Fill with next value', cleaner='fill_with_bfill', cleaner_id=None, activate=True, data=None)]),
 ScanResult(row=7, col=num3, message='Missing value in row 8, column 'num3'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Missing Value Filler', description='Fill with previous value', cleaner='fill_with_ffill', cleaner_id=None, activate=True, data=None)]),
 ScanResult(row=7, col=bool, message='Missing value in row 8, column 'bool'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Missing Value Filler', description='Delete the row', cleaner='delete_missing_rows', cleaner_id=None, activate=True, data=None)]),
 ScanResult(row=8, col=num2, message='Missing value in row 9, column 'num2'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Missing Value Filler', description='Fill with most frequent value', cleaner='fill_with_mode', cleaner_id=None, activate=True, data=None)]),
 ScanResult(row=12, col=num3, message='Missing value in row 13, column 'num3'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Missing Value Filler', description='Fill with median value', cleaner='fill_with_median', cleaner_id=None, activate=True, data=None)]),
 ScanResult(row=13, col=text, message='Missing value in row 14, column 'text'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Missing Value Filler', description='Fill with next value', cleaner='fill_with_bfill', cleaner_id=None, activate=True, data=None)]),
 ScanResult(row=14, col=bool, message='Missing value in row 15, column 'bool'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Missing Value Filler', description='Delete the row', cleaner='delete_missing_rows', cleaner_id=None, activate=True, data=None)]),
 ScanResult(row=15, col=num2, message='Missing value in row 16, column 'num2'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Missing Value Filler', description='Delete the row', cleaner='delete_missing_rows', cleaner_id=None, activate=True, data=None)]),
 ScanResult(row=16, col=num3, message='Missing value in row 17, column 'num3'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Missing Value Filler', description='Delete the row', cleaner='delete_missing_rows', cleaner_id=None, activate=True, data=None)]),
 ScanResult(row=17, col=bool, message='Missing value in row 18, column 'bool'', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Missing Value Filler', description='Delete the row', cleaner='delete_missing_rows', cleaner_id=None, activate=True, data=None)]),
 ScanResult(row=4, col=num5, message='Outlier detected in column 'num5' at row 5', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Outlier Handler', description='Delete the outlier', cleaner='delete_outlier', cleaner_id=None, activate=True, data=None)]),
 ScanResult(row=8, col=num5, message='Outlier detected in column 'num5' at row 9', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Outlier Handler', description='Delete the outlier', cleaner='delete_outlier', cleaner_id=None, activate=True, data=None)]),
 ScanResult(row=15, col=num5, message='Outlier detected in column 'num5' at row 16', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Outlier Handler', description='Delete the outlier', cleaner='delete_outlier', cleaner_id=None, activate=True, data=None)]),
 ScanResult(row=17, col=num5, message='Outlier detected in column 'num5' at row 18', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Outlier Handler', description='Delete the outlier', cleaner='delete_outlier', cleaner_id=None, activate=True, data=None)]),
 ScanResult(row=-1, col=cat1, message='Categorical feature 'cat1' detected with 3 categories: cherry, apple, banana', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Categorical Encoder', description='Apply one-hot encoding', cleaner='one_hot', cleaner_id=None, activate=True, data=None)]),
 ScanResult(row=-1, col=cat2, message='Categorical feature 'cat2' detected with 3 categories: green, blue, red', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Categorical Encoder', description='Apply one-hot encoding', cleaner='one_hot', cleaner_id=None, activate=True, data=None)]),
 ScanResult(row=-1, col=text, message='Categorical feature 'text' detected with 16 categories: Sample 0, Sample 1, Sample 2, Sample 5, Sample 6, Sample 7, Sample 8, Sample 9, Sample 11, Sample 12... (Total 16 categories)', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Categorical Encoder', description='Apply one-hot encoding', cleaner='one_hot', cleaner_id=None, activate=True, data=None)]),
 ScanResult(row=-1, col=bool, message='Categorical feature 'bool' detected with 2 categories: False, True', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Categorical Encoder', description='Drop the column', cleaner='drop', cleaner_id=None, activate=True, data=None)]),
 ScanResult(row=-1, col=cat3, message='Categorical feature 'cat3' detected with 3 categories: X, Y, Z', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Categorical Encoder', description='Apply one-hot encoding', cleaner='one_hot', cleaner_id=None, activate=True, data=None)]),
 ScanResult(row=-1, col=cat4, message='Categorical feature 'cat4' detected with 19 categories: a, b, c, d, e, f, g, h, i, j... (Total 19 categories)', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Categorical Encoder', description='Apply one-hot encoding', cleaner='one_hot', cleaner_id=None, activate=True, data=None)]),
 ScanResult(row=-1, col=cat5, message='Categorical feature 'cat5' detected with 1 categories: X', action_type=SRActionType.DEFAULT, actions=[ScanResultAction(title='Categorical Encoder', description='Drop the column', cleaner='drop', cleaner_id=None, activate=True, data=None)])]

In [6]:
for scan_result in scan_results:
    if scan_result.action_type == SRActionType.DEFAULT:
        if "duplicated" in scan_result.message:
            df1 = clean_df_for_duplicates(scan_result, df1)
        elif "Missing value" in scan_result.message:
            df1 = clean_df_for_missing(scan_result, df1)
        elif "Outlier detected" in scan_result.message:
            df1 = clean_df_for_outlier(scan_result, df1)
        elif "Categorical feature" in scan_result.message:
            df1 = clean_df_for_categorical(scan_result, df1)

df1

Row 8 not found in DataFrame.
Row 15 not found in DataFrame.
Row 17 not found in DataFrame.

d:\SEGP-G6\notebooks\data_clean_manual.py:61: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[scan_result.col].fillna(method='bfill', inplace=True)
d:\SEGP-G6\notebooks\data_clean_manual.py:61: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[scan_result.col].fillna(method='bfill', inplace=True)
d:\SEGP-G6\notebooks\data_clean_manual.py:59: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[scan_result.col].fillna(method='ffill', inplace=True)
d:\SEGP-G6\notebooks\data_clean_manual.py:59: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[scan_result.col].fillna(method='ffill', inplace=True)
d:\SEGP-G6\notebooks\data_clean_manual.py:57: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[scan_result.col].fillna(df[scan_result.col].mode()[0], inplace=True)
d:\SEGP-G6\notebooks\data_clean_manual.py:55: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[scan_result.col].fillna(df[scan_result.col].median(), inplace=True)
d:\SEGP-G6\notebooks\data_clean_manual.py:61: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[scan_result.col].fillna(method='bfill', inplace=True)
d:\SEGP-G6\notebooks\data_clean_manual.py:61: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[scan_result.col].fillna(method='bfill', inplace=True)

,num1,num2,num3,num4,num5,cat1_apple,cat1_banana,cat1_cherry,cat2_blue,cat2_green,...,cat4_d,cat4_f,cat4_g,cat4_j,cat4_l,cat4_m,cat4_n,cat4_q,cat4_s,cat4_t
0,51,14.623781,0.781820,34,-3.051610,False,False,True,False,True,...,False,False,False,False,False,False,False,False,False,False
1,92,15.387150,21.170074,192,-1.580829,True,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
3,71,6.034412,14.674409,174,-1.144238,False,False,True,False,True,...,True,False,False,False,False,False,False,False,False,False
5,20,-1.638671,9.942120,0,-1.048462,True,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
6,82,-14.763297,35.567098,4,-3.870215,False,True,False,False,True,...,False,False,True,False,False,False,False,False,False,False
9,74,3.555513,46.315044,26,-1.278823,False,True,False,False,True,...,False,False,False,True,False,False,False,False,False,False
11,99,8.324619,45.747984,14,-6.556621,False,True,False,False,False,...,False,False,False,False,True,False,False,False,False,False
12,23,-2.933991,45.747984,89,-4.351525,False,True,False,False,True,...,False,False,False,False,False,True,False,False,False,False
13,2,-0.298386,22.472534,41,-2.533216,True,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
16,1,-1.402185,4.770506,62,-5.481329,False,True,False,False,False,...,False,False,False,False,False,False,False,True,False,False
18,29,-7.490765,29.564889,51,-3.330303,False,True,False,False,False,...,False,False,False,False,False,False,False,False,True,False
19,37,-7.783820,13.736090,95,-2.568937,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,True

In [7]:
from data_clean_auto import *
df2

ModuleNotFoundError: No module named 'sklearn'

In [ ]:
df2 = clean_data(df2, handle_dates=True, generate_report=True)
df2